# Generated by Django 4.2.6 on 2023-11-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name_plural': 'Comunidades'},
        ),
    ]
