# Generated by Django 4.2.6 on 2023-11-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_hospedaje_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='destino',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
