# Generated by Django 4.2.6 on 2023-11-18 22:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_comunidad_creador_destino_creador_alter_post_creador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comunidad',
            new_name='Hospedaje',
        ),
        migrations.AlterModelOptions(
            name='hospedaje',
            options={},
        ),
    ]
