# Generated by Django 4.2.6 on 2023-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_comunidad_hospedaje_alter_hospedaje_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='imagen',
            field=models.ImageField(default=1, upload_to='hospedajes/'),
            preserve_default=False,
        ),
    ]
