# Generated by Django 4.2.6 on 2023-11-18 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_hospedaje_destino'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Articulo',
        ),
    ]
